### PR TITLE
Update system.prop

### PR DESCRIPTION
**Pull request by kushal10**
sim detection on msim variants

### CODE REVIEW

**Comment by Thecrazyskull** [comment]
Maintain authorship

**Comment by kushal10** [comment]
What do u mean by authorship ?

**Comment by kushal10** [comment]
What do u mean by authorship?

**Comment by h2o64** [comment]
I let thecrazyskull device but I put "-1"

**Comment by kushal10** [comment]
I'm unable to understand what you are trying to say..

**Comment by Thecrazyskull** [comment]
Then you shouldn't really expect this to be merged anywhere soon.

**Comment by kushal10** [comment]
I'll take authorship

**Comment by Thecrazyskull** [comment]
you shouldn't since this patch is not yours.

**Comment by kushal10** [comment]
I'll patch more on my own

**Comment by Thecrazyskull** [comment]
seriously learn what it is then create pull requests next time.

**Pull request closed without merging**
